version: '3'

services:
  jackal-s3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jackal-s3
    restart: always
    ports:
      - "3010:3000"
    environment:
      - JACKAL_MNEMONIC=${JACKAL_MNEMONIC}
      - ACCESS_KEY_ID=jackal
      - SECRET_ACCESS_KEY=jackalsecret
      - PORT=3000
    volumes:
      - jackal-s3:/tmp/jackal-s3

volumes:
  jackal-s3: