version: '3'

services:
  jackal-s3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jackal-s3
    restart: always
    ports:
      - 3010:${PORT}
    environment:
      - JACKAL_TESTNET_WALLET_MNEMONIC=${JACKAL_TESTNET_WALLET_MNEMONIC}
      - JACKAL_MAINNET_WALLET_MNEMONIC=${JACKAL_MAINNET_WALLET_MNEMONIC}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - PORT=${PORT}
      - NETWORK=${NETWORK}
      - BASE_FOLDER=${BASE_FOLDER}
    volumes:
      - jackal-s3:/tmp/jackal-s3

volumes:
  jackal-s3: